apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: myapp-argo-application
  namepsace: argocd
spec:
  project: default
  source:
    repoURL: "https://github.com/JoelSaleem/argo-test.git"
    targetRevision: HEAD
    path: "."
  destination:
    server: https://kubernetes.default.svc
    namespace: delete-me

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true